Wait for worker to be submitted in TestWorkerPoolLen
Occasionally, TestWorkerPoolLen will fail with:

=== RUN   TestWorkerPoolLen
    workerpool_test.go:90: got 0; want 1
--- FAIL: TestWorkerPoolLen (0.00s)

see e.g. https://github.com/cilium/workerpool/runs/5717463554?check_suite_focus=true

This seems to happen more often since switching to Go 1.18.

Fix this by waiting for the worker to be submitted before checking
(*WorkerPool).Len.

Signed-off-by: Tobias Klauser <tobias@cilium.io>